### PR TITLE
Fix #507

### LINKED ISSUE #507: Device names containing `/` cause problems
> Here's an icky situation I am facing wrt presets: IR identifies my mouse as "Logitech M585/590." Yep, you've read that right: there's a slash in there, and that confuses the hell out of my system. As a result, quite often IR doesn't load the proper profile upon reboot, so I have to load it manually. Is there any way we can control the name of the devices as far as IR is concerned?

_Originally posted by @Aqua1ung in https://github.com/sezanzeb/input-remapper/discussions/504_

### PR DESCRIPTION
**Pull request by jonasBoss**
I would hold back on merging this, until we can confirm it actually fixes #507

### CODE REVIEW

**Comment by sezanzeb** [comment]
Thanks. What about preset names that contain "/"?

**Comment by jonasBoss** [comment]
I guess we want to check those as well. But at a different place. 

The user can't do anything about a device with illegal characters. This fix will just silently change the folder name, but still show the original device name in the gui.

I don't think we want that for the preset name, because the user has control over it. There it would be better to just not create such a preset and warn the user about the illegal characters. Or maybe we can directly control the name input field to disallow illegal characters.

I think this is something we should do on the beta branch, I don't see the need to do it on main.

**Comment by sezanzeb** [comment]
lets just merge it, wait and see

**Comment by sezanzeb** [comment]
please merge it into beta

**Comment by sezanzeb** [comment]
> the merge of main into beta is somewhat problematic with this, because the tests need to be different

I'm working on it

**Pull request merged**
