### PR TITLE
Do not exclude buttonless devices that have axes

### PR DESCRIPTION
**Pull request by StelardActek**
Changes to groups.py to enable devices such as racing pedals (which have multiple axes but no buttons) to be remapped in the GUI.

### CODE REVIEW

**Comment by StelardActek** [comment]
Hey @sezanzeb, I'll do my best but I'm not actually a python dev so I'm not really familiar with how these things are done.
A look at the output suggests one issue is just a formatting issue, easy enough to fix. Another seems to be failing because it is testing that ABS-only devices are excluded, which is what I'm intending to change here. If I can find that test I'll see about changing it. The last one... I'm not sure what that is about.

**Comment by sezanzeb** [comment]
For the linter, you can get it to be formatted correctly quickly by doing

```
sudo apt install black
black input-remapper/inputremapper
```

(see https://github.com/psf/black)

There is luckily no need to do it by hand

**Comment by jonasBoss** [comment]
From my side the change looks good!

**Comment by sezanzeb** [comment]
I'll give it a try maybe tomorrow or something (just a quick test if gamepads still work and such, I don't have a foot pedal), and then merge it if there is no further objection.

**Comment by sezanzeb** [comment]
Thank you!

**Pull request merged**
