### PR TITLE
allow autoload command to execute if `config_dir` is provided

### PR DESCRIPTION
**Pull request by tmclane**
I have a Linux machine that does not show any `logged in users` with the `who` command even when I am using the machine.
It is perhaps a specialized use-case but I don't see why you need a logged in user in order to activate the mapping IF a config directory has been provided which contains the relevant configuration for key-mapper.

The machine in question is a JingPad A1.  

```
tmclane@JingOS:/media/tmclane/data/key-mapper$ who
tmclane@JingOS:/media/tmclane/data/key-mapper$ whoami
tmclane
```

### CODE REVIEW

**Comment by sezanzeb** [comment]
You are absolutely right!

But that won't fix autoloading at login (data/key-mapper-autoload.desktop) or device plugging (data/99-key-mapper.rules) on your system. Any ideas?

It's not critically important to not run key-mapper-control if no user is logged in. It just avoids some confusion when people see the log

**Comment by sezanzeb** [comment]
I have pushed a change to main that uses systemd-analyze, does that work for you?

**Comment by tmclane** [comment]
Let me give your changes a try.

FYI: I found another solution which was to put a script in: `/usr/lib/pm-utils/sleep.d` that calls the `key-mapper-control` command on sleep / wake to disable and reenable it.

Specifically this one: https://github.com/tmclane/jingpad/blob/main/99_jingpad_wakeup

**Comment by sezanzeb** [comment]
I think this can be closed, the change with `systemd-analyze` probably fixed this

**Pull request closed without merging**
