### PR TITLE
RelToAbs

### PR DESCRIPTION
**Pull request by jonasBoss**
needs tests

### CODE REVIEW

**Comment by jonasBoss** [comment]
This should be a good example for a `RelToRelHandler`

**Comment by sezanzeb** [comment]
image

Is this related to this PR?

**Comment by sezanzeb** [comment]
ah, I had to clear the text input. Now it says:

image

**Comment by jonasBoss** [comment]
Those have nothing to do with this PR. I created #468 for this, there we can collect all the problematic error messages and fix them.

**Comment by sezanzeb** [comment]
what should I do about the second error message in order to try the RelToAbs handler out?

**Comment by jonasBoss** [comment]
You need to configure the input as axis input. Go to the `Advanced Input Configuration` and set the flip the swich "Use as Analog"

**Comment by sezanzeb** [comment]
If no input is used as analog, but the mapping maps to "Analog Axis", can we default to using the first analog input as analog axis?

I think user experience is really one of the most important things in software. If we can somehow make it easier for people to use it I'm all for it.

**Comment by jonasBoss** [comment]
I can see what I can come up with.

**Comment by jonasBoss** [comment]
I just updated the GUI. It will now show a message when the user switches between "Key or Macro" and "Analog axis" and it will remove the macro input or the axis input to avoid errors. 
It is not perfect, the user still needs to update the input accordingly but hopefully it clears up some confusion. 

This needs some integration tests.

**Comment by jonasBoss** [comment]
@sezanzeb can you have another look at this? Should be ready.

**Comment by sezanzeb** [comment]
great! Thanks. It was easy to set it up

Can you please add a tooltip to "Output Axis" that says something like "Available output axes are affected by the Target setting."? I'll merge it then

**Comment by sezanzeb** [comment]
I just started working on the new UI, I'll add the tooltip later

**Pull request merged**
