### PR TITLE
fix python 3.8 compatability #278

### PR DESCRIPTION
**Pull request by jonasBoss**

### CODE REVIEW

**Comment by jonasBoss** [comment]
that did not work, for some reason it there are 55 files changed

**Comment by sezanzeb** [comment]
probably because I'm squashing all changes (including mine)

**Comment by jonasBoss** [comment]
makes sense

**Comment by sezanzeb** [comment]
does it? Why would it show

image

as a change

**Comment by jonasBoss** [comment]
I guess that is the last common commit in the history. Git does not know you merged all my commits via the PR

**Pull request closed without merging**
