### PR TITLE
Explain architecture in docs

### PR DESCRIPTION
**Pull request by sezanzeb**
Adds a miro board to development.md

also made the handler creation logs more readable by adding names to then

### CODE REVIEW

**Comment by sezanzeb** [comment]
@jonasBoss can you please help explain what is happening here:

```
13:34:14.492715 54046 Service DEBUG mapping_parser.py:135: event-pipeline with entry point: (1, 30)
13:34:14.492865 54046 Service DEBUG mapping_parser.py:136: HierarchyHandler for InputEvent(1, 30, 1) <139914993594912>:
13:34:14.492898 54046 Service DEBUG mapping_parser.py:136:     CombinationHandler for B + C + A <139914993131936>:
13:34:14.492924 54046 Service DEBUG mapping_parser.py:136:         KeyHandler <139914993131696>:
13:34:14.492946 54046 Service DEBUG mapping_parser.py:136:             maps to: (1, 4) on keyboard
13:34:14.492967 54046 Service DEBUG mapping_parser.py:136:     CombinationHandler for A + B + C <139914993132944>:
13:34:14.492988 54046 Service DEBUG mapping_parser.py:136:         KeyHandler <139914993133616>:
13:34:14.493009 54046 Service DEBUG mapping_parser.py:136:             maps to: (1, 2) on keyboard
13:34:14.493034 54046 Service DEBUG mapping_parser.py:136:     CombinationHandler for B + A <139914993593280>:
13:34:14.493054 54046 Service DEBUG mapping_parser.py:136:         KeyHandler <139914993592128>:
13:34:14.493075 54046 Service DEBUG mapping_parser.py:136:             maps to: (1, 3) on keyboard
13:34:14.493100 54046 Service DEBUG mapping_parser.py:135: event-pipeline with entry point: (1, 46)
13:34:14.493152 54046 Service DEBUG mapping_parser.py:136: HierarchyHandler for InputEvent(1, 46, 1) <139914993594432>:
13:34:14.493175 54046 Service DEBUG mapping_parser.py:136:     CombinationHandler for A + B + C <139914993132944>:
13:34:14.493196 54046 Service DEBUG mapping_parser.py:136:         KeyHandler <139914993133616>:
13:34:14.493215 54046 Service DEBUG mapping_parser.py:136:             maps to: (1, 2) on keyboard
13:34:14.493234 54046 Service DEBUG mapping_parser.py:136:     CombinationHandler for B + C + A <139914993131936>:
13:34:14.493253 54046 Service DEBUG mapping_parser.py:136:         KeyHandler <139914993131696>:
13:34:14.493273 54046 Service DEBUG mapping_parser.py:136:             maps to: (1, 4) on keyboard
13:34:14.493297 54046 Service DEBUG mapping_parser.py:135: event-pipeline with entry point: (1, 48)
13:34:14.493352 54046 Service DEBUG mapping_parser.py:136: HierarchyHandler for InputEvent(1, 48, 1) <139914993596016>:
13:34:14.493374 54046 Service DEBUG mapping_parser.py:136:     CombinationHandler for A + B + C <139914993132944>:
13:34:14.493395 54046 Service DEBUG mapping_parser.py:136:         KeyHandler <139914993133616>:
13:34:14.493414 54046 Service DEBUG mapping_parser.py:136:             maps to: (1, 2) on keyboard
13:34:14.493434 54046 Service DEBUG mapping_parser.py:136:     CombinationHandler for B + C + A <139914993131936>:
13:34:14.493453 54046 Service DEBUG mapping_parser.py:136:         KeyHandler <139914993131696>:
13:34:14.493471 54046 Service DEBUG mapping_parser.py:136:             maps to: (1, 4) on keyboard
13:34:14.493490 54046 Service DEBUG mapping_parser.py:136:     CombinationHandler for B + A <139914993593280>:
13:34:14.493507 54046 Service DEBUG mapping_parser.py:136:         KeyHandler <139914993592128>:
13:34:14.493525 54046 Service DEBUG mapping_parser.py:136:             maps to: (1, 3) on keyboard
```

preset:

```json
{
    "1,30,1+1,48,1+1,46,1": {
        "target_uinput": "keyboard",
        "output_symbol": "1",
        "mapping_type": "key_macro"
    },
    "1,48,1+1,46,1+1,30,1": {
        "target_uinput": "keyboard",
        "output_symbol": "3",
        "mapping_type": "key_macro"
    },
    "1,48,1+1,30,1": {
        "target_uinput": "keyboard",
        "output_symbol": "2",
        "mapping_type": "key_macro"
    }
}
```

so that I can draw it in the miro board

**Comment by sezanzeb** [comment]
is that about right?

image

**Comment by sezanzeb** [comment]
what would be an example for a setup that requires supress=True in notify?

**Comment by jonasBoss** [comment]
It is probably a good idea to include the order in which the each hierarchy handler triggers the different combination handlers:
 - A -> 1, 2, 3
 - B -> 2, 1, 3
 - C -> 2, 1

this order will create the different outputs:
```
  |----> y
A+B+C -> x
A+C+B -> x

  |----> y
B+A+C -> X
B+C+A -> z
C+A+B -> x
C+B+A -> z
```

The Hierarchy handler will always send the event to each sub handler to ensure they keep track of the input state even if they are not triggered.
When the user input is `B+C+A` the hierarchy handler for `A`  will first notify 1 and get a success return value. Now 2 and 3 are notified but with `suppress=True`. If we don't notify 2 and 3 it is possible that they might not trigger later on because they have the wrong state.

**Pull request merged**
