### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by nlepage**
Hello, here is a first attempt at a new french translation.

I'm having a hard time with 2 of the keys :
 - `msgid "with those after they are injected, and by doing so "`
 - `msgid "break them."`

I couldn't find these in the running application, so I'm not sure how to translate these...

### CODE REVIEW

**Comment by yngmjgsd** [comment]
> Hello, here is a first attempt at a new french translation.
> 
> I'm having a hard time with 2 of the keys :
> 
>     * `msgid "with those after they are injected, and by doing so "`
> 
>     * `msgid "break them."`
> 
> 
> I couldn't find these in the running application, so I'm not sure how to translate these...

The full phrase in English is:

`"Your system might reinterpret combination with those after they are injected, and by doing so break them."`

This is a dialog box and you will not see it normally in UI. See `editor.py` for more information.

**Comment by sezanzeb** [comment]
Thanks. I'll check it out soon, I'm busy with exams right now

**Comment by nlepage** [comment]
> The full phrase in English is:
> 
> `"Your system might reinterpret combination with those after they are injected, and by doing so break them."`

Thanks, this helped me finish the translation.

**Comment by sezanzeb** [comment]
Ah, yeah this message is constructed incorrectly, I'll change it in beta from

```py
                _("Your system might reinterpret combinations ")
                + _("with those after they are injected, and by doing so ")
                + _("break them."),
```

to 

```py
                _(
                    "Your system might reinterpret combinations " +
                    "with those after they are injected, and by doing so " +
                    "break them."
                ),
```

**Comment by sezanzeb** [comment]
Thanks a lot.

The beta branch will need new translations as well. I'm aiming for a release within a month

**Pull request merged**
