### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by rffontenelle** [comment]
Unable to pass this issue. Looks like more a code than CI issue

```
Traceback (most recent call last):
  File "/home/runner/work/input-remapper/input-remapper/tests/test.py", line 70, in <module>
    import tests.test
  File "/home/runner/work/input-remapper/input-remapper/tests/__init__.py", line 2, in <module>
    import tests.test
  File "/home/runner/work/input-remapper/input-remapper/tests/test.py", line 124, in <module>
    patch_regrab_timeout()
  File "/home/runner/work/input-remapper/input-remapper/tests/lib/patches.py", line 304, in patch_regrab_timeout
    from inputremapper.injection.injector import Injector
  File "/usr/local/lib/python3.10/dist-packages/inputremapper/injection/injector.py", line 37, in <module>
    from inputremapper.configs.preset import Preset
  File "/usr/local/lib/python3.10/dist-packages/inputremapper/configs/preset.py", line 41, in <module>
    from inputremapper.configs.mapping import Mapping, UIMapping
  File "/usr/local/lib/python3.10/dist-packages/inputremapper/configs/mapping.py", line 63, in <module>
    from inputremapper.gui.gettext import _
  File "/usr/local/lib/python3.10/dist-packages/inputremapper/gui/gettext.py", line 27, in <module>
    LOCALE_DIR = os.path.join(get_data_path(), "lang")
  File "/usr/local/lib/python3.10/dist-packages/inputremapper/configs/data.py", line 89, in get_data_path
    data = _try_python_package_location() or _try_standard_locations()
  File "/usr/local/lib/python3.10/dist-packages/inputremapper/configs/data.py", line 49, in _try_standard_locations
    return data
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by sezanzeb** [comment]
in `_try_standard_locations` data should be initialized with None

Afterwards the error message will make a bit more sense: `Could not find the application data`

**Comment by rffontenelle** [comment]
I see. So it is looking for the app data, which doesn't exist in CI due to the way it is being tested?

**Comment by sezanzeb** [comment]
Add `-vvv` to `sudo pip install --no-binary :all: .` to see where files go

**Comment by sezanzeb** [comment]
Are you planning to look into it?

**Comment by rffontenelle** [comment]
This is rather an interesting issue.

While the datadir is being installed into `/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/usr/share/input-remapper` (for python 3.11, obviously), `pkg_resources.require("input-remapper")[0].location)` returns `/home/runner/work/input-remapper/input-remapper` (source checkout directory).

So, data.py's [_try_standard_locations](https://github.com/sezanzeb/input-remapper/blob/main/inputremapper/configs/data.py#L35) doesn't find in usual */share/input-remapper directories, nor [_try_python_package_location](https://github.com/sezanzeb/input-remapper/blob/main/inputremapper/configs/data.py#L52) finds it in the Python site-packages.

**Comment by sezanzeb** [comment]
Ah, found it.

Installing data files with python is a nightmare

**Comment by sezanzeb** [comment]
Maybe something can be worked out using --root or --prefix https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-root

**Comment by sezanzeb** [comment]
If that doesn't completely resolve the issue, I'd possibly extend `get_data_path` to call something like `_try_ci_locations`

**Comment by rffontenelle** [comment]
Haven't tested in here, but I've used this scenario before. GitHub Actions set `$CI`, so a `CI in os.environ` conditional expression should work. I'll test it later and let you know.

**Comment by sezanzeb** [comment]
hm, I would rather have a variable like `DATA_PATH`, so that no commits to the python code are required to configure the ci

**Comment by sezanzeb** [comment]
There is `XDG_DATA_DIRS`, `get_data_path` should probably iterate over those as well (unless `DATA_DIR` is set)

**Comment by sezanzeb** [comment]
Are you going to try it? Otherwise I'll work on it

**Comment by sezanzeb** [comment]
See https://github.com/sezanzeb/input-remapper/pull/730

**Pull request closed without merging**
