### PR TITLE
Merge main into beta

### PR DESCRIPTION
**Pull request by jonasBoss**

### CODE REVIEW

**Comment by sezanzeb** [comment]
I can't find the changes from commits [3a48d26](https://github.com/sezanzeb/input-remapper/pull/421/commits/3a48d2680e013f5fb0f2d024dad7290511d45cef) and [96950e8](https://github.com/sezanzeb/input-remapper/pull/421/commits/96950e83878be7117b91e3ed56aa656123b32f04)

**Comment by sezanzeb** [comment]
that's weird, when I browse your branch it's there. It's just not shown in the "Files changed" page

**Comment by jonasBoss** [comment]
That is strange. I can see what you mean. maybe GitHub thinks they are already merged (which is clearly wrong). 
Can you merge my beta branch locally? Then you can check with a diff that all changes are merged.

**Comment by sezanzeb** [comment]
I think everything up to 

image

is already on the beta branch

**Comment by jonasBoss** [comment]
I don't think so. I never made a PR for that.

**Comment by sezanzeb** [comment]
https://github.com/sezanzeb/input-remapper/pull/399

**Comment by jonasBoss** [comment]
Okay I am a bit confused. Still strange that github shows them in the commit history of this pr.

**Comment by jonasBoss** [comment]
You are right they are all on beta already.

**Pull request merged**
